name: Code Format Check

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Beautify:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -qq -y install uncrustify

    - name: Run beautify
      run: ./scripts/beautify.sh --check
