name: Code Format Check

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Beautify:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -qq -y install clang-format

    - name: Run beautify
      run: |
        set -x
        cp -r . ${{ runner.temp }}/a
        cp -r . ${{ runner.temp }}/b
        cd ${{ runner.temp }}/b
        ./scripts/beautify.sh --all
        cd ${{ runner.temp }}
        diff -r a b | tee ${{ runner.temp }}/beautify.patch

    - name: Upload patch artifact
      uses: actions/upload-artifact@v4
      with:
        name: beautify-patch
        path: ${{ runner.temp }}/beautify.patch
